name: Doxygen_on_master
on:
  push:
    paths:
    - 'code/**'
    branches:
    - master
jobs:
  publish:
    - uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'code/MVP/'
        doxyfile-path: 'docs/'
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: gh-pages
        github_token: '${{ secrets.GITHUB_TOKEN  }}'
        github_pat: '${{ secrets.GH_PAT }}'
        source_folder: code/MVP/docs/
      if: success() && github.event == 'push'
