# GitHub Action that enables a repo to achieve gradual compliance with cpplint by
#     linting only those files that have been added or modified (vs. origin/master).
# 1. runs cpplint only on those files that have been modified vs. origin/master.
# 2. compiles with g++ only those files that have been modified vs. origin/master.
# 3. other optional filepath verifications may be commented out at the end of this file.
# From: https://github.com/cpplint/GitHub-Action-for-cpplint

name: cpplint_modified_files
on:
  pull_request:
    paths:
    - 'code/**'
    branches:
      - master
      - 'develop/**'
jobs:
  cpplint_modified_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - shell: python  # Show the version of shell: python and then upgrade shell: python to Python 3.9
        run: import sys ; print("Python {}.{}.{}".format(*sys.version_info))  # Legacy Python :-(
      - run: sudo update-alternatives --install /usr/bin/python python ${pythonLocation}/bin/python3.9 10
      - run: python -m pip install cpplint
      - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - run: git diff origin/$GITHUB_REF --name-only > git_diff.txt
      - name: cpplint_modified_files
        shell: python
        run: |
          import os
          import re
          import subprocess
          import sys
          print("Python {}.{}.{}".format(*sys.version_info))  # Python 3.8
          with open("git_diff.txt") as in_file:
            modified_files = sorted(in_file.read().splitlines())
          print("{} files were modified.".format(len(modified_files)))
          cpp_exts = tuple(".c .c++ .cc .cpp .cu .cuh .cxx .h .h++ .hh .hpp .hxx".split())
          cpp_files = [file for file in modified_files if file.lower().endswith(cpp_exts)]
          print(f"{len(cpp_files)} C++ files were modified.")
          if not cpp_files:
            sys.exit(0)
          regex_rootdir = r"^/?code/[^/\s\r\n]*/"
          rootdir_list = []
          for filename in cpp_files:
            rootdir_extract = re.finditer(regex, filename, re.MULTILINE)
            if rootdir_extract and not rootdir in rootdir_list:
              rootdir_list.append(rootdir_extract)
          for rootdir in rootdir_list:
            files_in_rootlist = []
            for file in cpp_files:
              file.startswith( rootdir )
              files_in_rootlist.append(file)
            print("cpplint: runs on rootdir " + rootdir)
            subprocess.run(["cpplint.py ",  "--root=" + rootdir + " --filter=-legal/copyright,-build/" ] + files_in_rootlist, check=True, text=True)
            print("g++:")
            subprocess.run(["g++"] + files_in_rootlist, check=True, text=True)

