---
name: Follow Leader
on:
  push:
    branches: master
jobs:
  rebaseAir:
    name: Rebase SchwurblAir
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: SchwurblAir
        uses: actions/checkout@v2
        with:
          ref: develop/SchwurblAir
      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: App Date Bot
          email: appdate@example.com
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
      - run: git status
      - run: |
          git diff --quiet develop/SchwurblAir origin/develop/SchwurblAir || \
          git push -f || (echo "Git force push failed" && exit 101)
          echo "SchwurblAir Rebased"

  rebase360:
    name: Rebase Schwurbler360
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Schwurbl360
        uses: actions/checkout@v2
        with:
          ref: develop/Schwurbler360
      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: App Date Bot
          email: appdate@example.com
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
      - run: |
          git diff --quiet develop/SchwurblAir origin/develop/Schwurbl360 || \
          git push -f || (echo "Git force push failed" && exit 101)
          echo "Schwurbl360 Rebased"

  rebaseTogo:
    name: Rebase ToGo
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Togo
        uses: actions/checkout@v2
        with:
          ref: develop/ToGo
      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: App Date Bot
          email: appdate@example.com
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
      - run: |
          git diff --quiet develop/SchwurblAir origin/develop/ToGo || \
          git push -f || (echo "Git force push failed" && exit 101)
          echo "ToGo  Rebased"
