name: Follow Master
on:
  push:
    branches:
      - master
jobs:
  follow-master:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    - uses: actions/checkout@v2
      with:
        ref: develop/SchwurblAir
    - run: |
        git rebase master || (git rebase --abort && echo "Merge conflicts happened" && exit 100)
        git push -f origin develop/SchwurblAir || (echo "Git force push failed" && exit 101)
        echo "SchwurblAir Rebased"
        git checkout -b develop/Schwurbler360 origin/develop/Schwurbler360
        git rebase master || (git rebase --abort && echo "Merge conflicts happened" && exit 100)
        git push -f origin develop/SchwurblAir || (echo "Git force push failed" && exit 101)
        echo "Schwurbl360 Rebased"
        git checkout -b develop/ToGo origin/develop/ToGo
        git rebase master || (git rebase --abort && echo "Merge conflicts happened" && exit 100)
        git push -f origin develop/ToGo || (echo "Git force push failed" && exit 101)
        echo "ToGo  Rebased"
