---
name: Follow Master
on:
  push:
    branches: master
jobs:
  dev-follow-master:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop/SchwurblAir
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
          git push -f || (echo "Git force push failed" && exit 101)
          echo "SchwurblAir Rebased"

      - uses: actions/checkout@v2
        with:
          ref: develop/SchwurblAir
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
          git push -f || (echo "Git force push failed" && exit 101)
          echo "Schwurbl360 Rebased"

      - uses: actions/checkout@v2
        with:
          ref: develop/ToGo
      - run: |
          git rebase master || \
          (git rebase --abort && echo "Merge conflicts happened" && exit 100)
          git push -f || (echo "Git force push failed" && exit 101)
          echo "ToGo  Rebased"
