name: Code Documentation
on:
  push:
    branches: master
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Builds the documentation
      - uses: mattnotmitt/doxygen-action@v1.2.0
        with:
          working-directory: './code/MVP/'
          doxyfile-path: './Doxyfile'
      - uses: mattnotmitt/doxygen-action@v1.2.0
        with:
          working-directory: './code/Schwurbler360/'
          doxyfile-path: './Doxyfile'
      - uses: mattnotmitt/doxygen-action@v1.2.0
        with:
          working-directory: 'code/SchwurblAir/'
          doxyfile-path: './Doxyfile'
      - run: |
          [ -d  "code/MVP/docs" ] &&  code/MVP/docs code/docs/MVP/
          [ -d  "code/Schwurbler360/docs" ] && mv code/Schwurbler360/docs code/docs/Schwurbler360/
          [ -d  "code/SchwurblAir/docs" ] && mv code/SchwurblAir/docs code/docs/SchwurblAir/
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: update-docs
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: code/docs/
        if: success() && github.event == 'push'
